/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTransactionsRouteImport } from './routes/app.transactions'
import { Route as AppSendRouteImport } from './routes/app.send'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AdminSocRouteImport } from './routes/admin.soc'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminResetPasswordRouteImport } from './routes/admin.reset-password'
import { Route as AdminRecoverRouteImport } from './routes/admin.recover'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminIpsRouteImport } from './routes/admin.ips'
import { Route as AdminFraudRouteImport } from './routes/admin.fraud'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminControlRouteImport } from './routes/admin.control'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAccountsRouteImport } from './routes/admin.accounts'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppSendRoute = AppSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AdminSocRoute = AdminSocRouteImport.update({
  id: '/soc',
  path: '/soc',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecoverRoute = AdminRecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIpsRoute = AdminIpsRouteImport.update({
  id: '/ips',
  path: '/ips',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFraudRoute = AdminFraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminControlRoute = AdminControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/control': typeof AdminControlRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/ips': typeof AdminIpsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/recover': typeof AdminRecoverRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/soc': typeof AdminSocRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/profile': typeof AppProfileRoute
  '/app/send': typeof AppSendRoute
  '/app/transactions': typeof AppTransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/control': typeof AdminControlRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/ips': typeof AdminIpsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/recover': typeof AdminRecoverRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/soc': typeof AdminSocRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/profile': typeof AppProfileRoute
  '/app/send': typeof AppSendRoute
  '/app/transactions': typeof AppTransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/control': typeof AdminControlRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/ips': typeof AdminIpsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/recover': typeof AdminRecoverRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/soc': typeof AdminSocRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/profile': typeof AppProfileRoute
  '/app/send': typeof AppSendRoute
  '/app/transactions': typeof AppTransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/reset-password'
    | '/admin/accounts'
    | '/admin/analytics'
    | '/admin/control'
    | '/admin/dashboard'
    | '/admin/fraud'
    | '/admin/ips'
    | '/admin/login'
    | '/admin/recover'
    | '/admin/reset-password'
    | '/admin/security'
    | '/admin/soc'
    | '/app/alerts'
    | '/app/dashboard'
    | '/app/profile'
    | '/app/send'
    | '/app/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/reset-password'
    | '/admin/accounts'
    | '/admin/analytics'
    | '/admin/control'
    | '/admin/dashboard'
    | '/admin/fraud'
    | '/admin/ips'
    | '/admin/login'
    | '/admin/recover'
    | '/admin/reset-password'
    | '/admin/security'
    | '/admin/soc'
    | '/app/alerts'
    | '/app/dashboard'
    | '/app/profile'
    | '/app/send'
    | '/app/transactions'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/reset-password'
    | '/admin/accounts'
    | '/admin/analytics'
    | '/admin/control'
    | '/admin/dashboard'
    | '/admin/fraud'
    | '/admin/ips'
    | '/admin/login'
    | '/admin/recover'
    | '/admin/reset-password'
    | '/admin/security'
    | '/admin/soc'
    | '/app/alerts'
    | '/app/dashboard'
    | '/app/profile'
    | '/app/send'
    | '/app/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/send': {
      id: '/app/send'
      path: '/send'
      fullPath: '/app/send'
      preLoaderRoute: typeof AppSendRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/soc': {
      id: '/admin/soc'
      path: '/soc'
      fullPath: '/admin/soc'
      preLoaderRoute: typeof AdminSocRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recover': {
      id: '/admin/recover'
      path: '/recover'
      fullPath: '/admin/recover'
      preLoaderRoute: typeof AdminRecoverRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ips': {
      id: '/admin/ips'
      path: '/ips'
      fullPath: '/admin/ips'
      preLoaderRoute: typeof AdminIpsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fraud': {
      id: '/admin/fraud'
      path: '/fraud'
      fullPath: '/admin/fraud'
      preLoaderRoute: typeof AdminFraudRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/control': {
      id: '/admin/control'
      path: '/control'
      fullPath: '/admin/control'
      preLoaderRoute: typeof AdminControlRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminControlRoute: typeof AdminControlRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFraudRoute: typeof AdminFraudRoute
  AdminIpsRoute: typeof AdminIpsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRecoverRoute: typeof AdminRecoverRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSocRoute: typeof AdminSocRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountsRoute: AdminAccountsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminControlRoute: AdminControlRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFraudRoute: AdminFraudRoute,
  AdminIpsRoute: AdminIpsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminRecoverRoute: AdminRecoverRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSocRoute: AdminSocRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSendRoute: typeof AppSendRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppSendRoute: AppSendRoute,
  AppTransactionsRoute: AppTransactionsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
